version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--max_old_space_size=4096
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - app-network
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    networks:
      - app-network
networks:
  app-network:
    driver: bridge