name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Run unit tests for frontend
        run: |
          cd frontend
          npm install
          npm test

      - name: Run unit tests for backend
        run: |
          cd backend
          python -m pip install -r requirements.txt
          python -m pytest

      - name: Run containers for integration tests
        run: |
          docker-compose -f docker-compose.yml up -d
          sleep 90
          docker ps
          docker logs frontend
          docker logs backend

      - name: Test backend API
        run: |
          curl --fail http://localhost:5000/api || echo "Backend test failed"

      - name: Test frontend
        run: |
          curl --fail http://localhost:3000 || echo "Frontend test failed"

      - name: Stop containers
        run: |
          docker-compose -f docker-compose.yml down